#
# Generated by Elyra 3.16.7
#
import kfp
from kubernetes.client import *
from kubernetes.client.models import *
from kfp.kubernetes import secret, volume

from typing import Optional

# ------------------------------------------------------------------
# kfp-kubernetes 1.1.0 is misisng these function, explicity using them,
# TODO: remove these function once a new release of kfp-kubernetes is made.
# ------------------------------------------------------------------

from google.protobuf import json_format
from kfp.dsl import PipelineTask
from kfp.kubernetes import common
from kfp.kubernetes import kubernetes_executor_config_pb2 as pb

from kfp.kubernetes import add_toleration, add_pod_label, add_pod_annotation


component_def_732a258451615564536dba7c90de81929423912d3c5673e839da6092f1bb7f5a = """
name: Run a file
description: Run a Jupyter notebook or Python/R script

inputs:
- {name: file_identifier, type: String, optional: false}

implementation:
  container:
    image: quay.io/modh/runtime-images@sha256:0a3c137492e66c5fac89786f90dbbfdfd3eecd8d9c0e4e890aeeb8f558cd731d
    command: [sh, -c]
    args:
    - |
      file_identifier="$0"
      sh -c "mkdir -p ./jupyter-work-dir && cd ./jupyter-work-dir"
      sh -c "echo 'Downloading file:///opt/app-root/bin/utils/bootstrapper.py' && curl --fail -H 'Cache-Control: no-cache' -L file:///opt/app-root/bin/utils/bootstrapper.py --output bootstrapper.py"
      sh -c "echo 'Downloading file:///opt/app-root/bin/utils/requirements-elyra.txt' && curl --fail -H 'Cache-Control: no-cache' -L file:///opt/app-root/bin/utils/requirements-elyra.txt --output requirements-elyra.txt"
      sh -c "python3 -m pip install  packaging && python3 -m pip freeze > requirements-current.txt && python3 bootstrapper.py --pipeline-name 'pdf-to-xml-var' --cos-endpoint 'https://minio-api-safra-ai.apps.rosa-5hxrw.72zm.p1.openshiftapps.com' --cos-bucket 'pipelines' --cos-directory 'pdf-to-xml-var-0804021609' --cos-dependencies-archive 'pdf-to-xml-var-1088e083-cdb9-4757-92de-8db6a96794a8.tar.gz' --file 'pdf-to-xml-var.py' --pipeline-parameters 'file_identifier=$file_identifier' --parameter-pass-method 'env' "
    - {inputValue: file_identifier}
"""

factory_732a258451615564536dba7c90de81929423912d3c5673e839da6092f1bb7f5a = (
    kfp.components.load_component_from_text(
        component_def_732a258451615564536dba7c90de81929423912d3c5673e839da6092f1bb7f5a
    )
)


@kfp.dsl.pipeline(name="pdf-to-xml-var")
def generated_pipeline(
    file_identifier: str = "22_95658203015_2023_2024",
):

    # Task for node 'pdf-to-xml-var'
    task_1088e083_cdb9_4757_92de_8db6a96794a8 = (
        factory_732a258451615564536dba7c90de81929423912d3c5673e839da6092f1bb7f5a(
            file_identifier=file_identifier,
        )
    )

    secret.use_secret_as_env(
        task_1088e083_cdb9_4757_92de_8db6a96794a8,
        "dashboard-dspa-secret",
        {
            "AWS_ACCESS_KEY_ID": "AWS_ACCESS_KEY_ID",
            "AWS_SECRET_ACCESS_KEY": "AWS_SECRET_ACCESS_KEY",
        },
    )

    task_1088e083_cdb9_4757_92de_8db6a96794a8.set_display_name("pdf-to-xml-var")

    task_1088e083_cdb9_4757_92de_8db6a96794a8.set_cpu_request(cpu="2")

    task_1088e083_cdb9_4757_92de_8db6a96794a8.set_memory_request(memory="2G")

    task_1088e083_cdb9_4757_92de_8db6a96794a8.set_cpu_limit(cpu="8")

    task_1088e083_cdb9_4757_92de_8db6a96794a8.set_memory_limit(memory="8G")

    task_1088e083_cdb9_4757_92de_8db6a96794a8.set_env_variable(
        name="ELYRA_RUNTIME_ENV", value="kfp"
    )

    task_1088e083_cdb9_4757_92de_8db6a96794a8.set_env_variable(
        name="ELYRA_ENABLE_PIPELINE_INFO", value="True"
    )

    task_1088e083_cdb9_4757_92de_8db6a96794a8.set_env_variable(
        name="ELYRA_WRITABLE_CONTAINER_DIR", value="/tmp"
    )

    task_1088e083_cdb9_4757_92de_8db6a96794a8.set_env_variable(
        name="ELYRA_RUN_NAME", value="{{workflow.uid}}"
    )

    add_pod_label(
        task_1088e083_cdb9_4757_92de_8db6a96794a8, "elyra/node-type", "notebook-script"
    )

    add_pod_label(
        task_1088e083_cdb9_4757_92de_8db6a96794a8,
        "elyra/pipeline-name",
        "pdf-to-xml-var",
    )

    add_pod_label(
        task_1088e083_cdb9_4757_92de_8db6a96794a8, "elyra/pipeline-version", ""
    )

    add_pod_label(
        task_1088e083_cdb9_4757_92de_8db6a96794a8, "elyra/experiment-name", ""
    )

    add_pod_label(
        task_1088e083_cdb9_4757_92de_8db6a96794a8, "elyra/node-name", "pdf-to-xml-var"
    )

    add_pod_annotation(
        task_1088e083_cdb9_4757_92de_8db6a96794a8,
        "elyra/node-file-name",
        """pdf-to-xml-var.py""",
    )

    add_pod_annotation(
        task_1088e083_cdb9_4757_92de_8db6a96794a8,
        "elyra/pipeline-source",
        """pdf-to-xml-var.pipeline""",
    )


if __name__ == "__main__":
    from pathlib import Path

    kfp.compiler.Compiler().compile(
        pipeline_func=generated_pipeline,
        package_path=Path(__file__).with_suffix(".yaml").name,
    )
